Repository wafflestudio/gatgu-server, pull requests merged in 2021-06, with the labels that each got.

#144 Feature/#142
  gatgu/article/views.py
  gatgu/gatgu/settings.py
  gatgu/gatgu/urls.py
  gatgu/requirements.txt
  gatgu/user/serializers.py
  gatgu/user/views.py
Labels: bug

#148 Feature/#145
  gatgu/gatgu/middleware.py
  gatgu/gatgu/settings.py
  gatgu/gatgu/urls.py
  gatgu/gatgu/utils.py
  gatgu/user/migrations/0002_auto_20210603_0614.py
  gatgu/user/migrations/0003_auto_20210604_1117.py
  gatgu/user/models.py
  gatgu/user/serializers.py
  gatgu/user/views.py
Labels: enhancement

#150 set simple order status
  gatgu/article/views.py
  gatgu/chat/models.py
  gatgu/chat/views.py
  gatgu/user/views.py
Labels: enhancement

#153 Feature/#152
  gatgu/article/migrations/0002_auto_20210608_0900.py
  gatgu/article/migrations/0003_auto_20210608_1725.py
  gatgu/article/models.py
  gatgu/article/serializers.py
  gatgu/article/views.py
  gatgu/chat/migrations/0002_auto_20210608_0900.py
  gatgu/chat/serializers.py
  gatgu/gatgu/settings.py
  gatgu/gatgu/utils.py
  gatgu/user/migrations/0004_auto_20210608_1725.py
  gatgu/user/models.py
  gatgu/user/serializers.py
  gatgu/user/views.py
Labels: enhancement

#172 Feature/#171
  .gitignore
  gatgu/article/migrations/0011_auto_20210621_1240.py
  gatgu/article/models.py
  gatgu/article/serializers.py
  gatgu/article/views.py
  gatgu/gatgu/settings.py
  gatgu/user/migrations/0005_auto_20210621_1240.py
  gatgu/user/models.py
  gatgu/user/serializers.py
  gatgu/user/views.py
Labels: enhancement

#174 [#174] Rds setting
  gatgu/gatgu/settings.py
Labels: build structure
