Repository wafflestudio/gatgu-server, pull requests merged in 2021-08, with the labels that each got.

#207 [#206] Edit image update logic & check timestamp format
  gatgu/article/migrations/0014_auto_20210731_1733.py
  gatgu/article/models.py
  gatgu/article/serializers.py
  gatgu/article/views.py
  gatgu/gatgu/settings.py
  gatgu/gatgu/utils.py
  gatgu/user/serializers.py
  gatgu/user/views.py
Labels: bug

#211 Feature/#203
  .github/workflows/deploy.yml
  gatgu/.ebextensions/cron-leaderonly-linux.config
  gatgu/.ebextensions/nginx_tmp/conf.d/gatgu.conf
  gatgu/.ebextensions/static-files_tmp
  gatgu/.ebextensions_xx/static-files.config
  gatgu/article/serializers.py
  gatgu/article/views.py
  gatgu/chat/views.py
  gatgu/gatgu/cron.py
  gatgu/gatgu/settings.py
  gatgu/gatgu/tasks.sh
  gatgu/gatgu/urls.py
  gatgu/push_notification/views.py
  gatgu/requirements.txt
  gatgu/user/serializers.py
  gatgu/user/views.py
Labels: enhancement, deploy_setting

#212 chat api 개선, 채팅알림
  gatgu/chat/consumers.py
  gatgu/chat/migrations/0008_auto_20210807_0205.py
  gatgu/chat/models.py
  gatgu/chat/views.py
  gatgu/requirements.txt
Labels: enhancement
